/* eslint-disable */
/**
 * Generated API listing.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.32.0.
 *
 * You can regenerate this file by running `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as cycles from "../cycles.js";
import type * as items from "../items.js";
import type * as settings from "../settings.js";
import type * as users from "../users.js";

/**
 * A type-safe API interface to the Convex functions in this project.
 */
export declare const api: FilterApi<
  ApiFromModules<{
    cycles: typeof cycles;
    items: typeof items;
    settings: typeof settings;
    users: typeof users;
  }>,
  FunctionReference<any, "public">
>;
