/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.32.0.
 *
 * You can regenerate this file by running `npx convex dev`.
 * @module
 */

import type {
  DataModelFromSchema,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNamesInDataModel,
  Id,
} from "convex/server";
import type schema from "../schema.js";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = TableNamesInDataModel<DataModel>;

/**
 * The type of a document in one of your Convex tables.
 */
export type Doc<TableName extends TableNames> = DocumentByName<
  DataModel,
  TableName
>;

/**
 * A type-safe database ID.
 */
export type Id<TableName extends TableNames | SystemTableNamesInDataModel<DataModel>> =
  Id<TableName>;

/**
 * The type of your Convex data model.
 */
export type DataModel = DataModelFromSchema<typeof schema>;

export default DataModel;
