/* eslint-disable */
/**
 * Generated helper functions.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.32.0.
 *
 * You can regenerate this file by running `npx convex dev`.
 * @module
 */

import type {
  ActionBuilder,
  AnyDataModel,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
} from "convex/server";
import type { DataModel } from "./dataModel.d.ts";

/**
 * Define a query in this Convex app. A query function can read from the database.
 *
 * @param func - The query function.
 */
export declare const query: QueryBuilder<DataModel, "public">;

/**
 * Define a mutation in this Convex app. A mutation function can read from and write to the database.
 *
 * @param func - The mutation function.
 */
export declare const mutation: MutationBuilder<DataModel, "public">;

/**
 * Define an action in this Convex app. An action function can read from and write to the database and make external requests.
 *
 * @param func - The action function.
 */
export declare const action: ActionBuilder<DataModel, "public">;

/**
 * Define an HTTP action in this Convex app.
 *
 * @param func - The HTTP action function.
 */
export declare const httpAction: HttpActionBuilder;

/**
 * The type of a query context.
 */
export type QueryCtx = GenericQueryCtx<DataModel>;

/**
 * The type of a mutation context.
 */
export type MutationCtx = GenericMutationCtx<DataModel>;

/**
 * The type of an action context.
 */
export type ActionCtx = GenericActionCtx<DataModel>;
